#Apply to all files without commiting:
#   pre-commit run --all-files
#Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
    language_version: python3.11