import sys

"""
SETTINGS -> exchange_coins.xlsx
Exchanges : BINANCE, BITFINEX, BITSTAMP, FTX, GEMINI, KUCOIN, POLONIEX

BINANCE  :  BTC/USDT,ETH/USDT,LTC/USDT,NEO/USDT,BNB/USDT,XRP/USDT,LINK/USDT,EOS/USDT,TRX/USDT,ETC/USDT,XLM/USDT,ZEC/USDT,ADA/USDT,QTUM/USDT,DASH/USDT,XMR/USDT,BAT/USDT,BTT/USDT,ZEC/USDT,USDC/USDT,TUSD/USDT,MATIC/USDT,PAX/USDT,CELR/USDT,ONE/USDT,DOT/USDT,UNI/USDT,ICP/USDT,SOL/USDT,VET/USDT,FIL/USDT,AAVE/USDT,DAI/USDT,MKR/USDT,ICX/USDT,CVC/USDT,SC/USDT,LRC/USDT,ADA/BTC,AST/BTC,BTG/BTC,DASH/BTC,EOS/BTC,ETC/BTC,ETH/BTC,IOTA/BTC,LTC/BTC,NEO/BTC,STRAT/BTC,XMR/BTC,XLM/BTC,XRP/BTC,XLM/ETH,XMR/ETH,XRP/ETH,NEO/ETH,LSK/ETH,IOTA/ETH,ETC/ETH,DASH/ETH,BTG/ETH
BITFINEX :  BTC/USD,ETH/USD,LTC/USD,AID/USD,BAT/USD,LTC/USD,DAI/USD,DASH/USD,EDO/USD,EOS/USD,ETC/USD,ETP/USD,NEO/USD,OMG/USD,QTUM/USD,REP/USD,TRX/USD,XLM/USD,XMR/USD,XVG/USD,BTC/EUR,ETH/EUR,EOS/EUR,NEO/EUR,TRX/EUR,XLM/EUR,XVG/EUR,BTC/GBP,ETH/GBP,EOS/GBP,NEO/GBP,TRX/GBP,XLM/GBP,XVG/GBP,BTC/JPY,ETH/JPY,EOS/JPY,NEO/JPY,TRX/JPY,XLM/JPY,XVG/JPY,ETH/BTC,LTC/BTC,XRP/BTC,DAI/BTC,DASH/BTC,EOS/BTC,OMG/BTC,REP/BTC,TRX/BTC,XMR/BTC
BITSTAMP :  BTC/USD,ETH/USD,LTC/USD,XRP/USD,BCH/USD,BTC/EUR,ETH/EUR,LTC/EUR,BCH/EUR,ETH/BTC,LTC/BTC,BCH/BTC,BTC/USD,BCH/USD,ETH/USD,LTC/USD,XRP/USD,BTC/EUR,BCH/EUR,ETH/EUR,LTC/EUR,XRP/EUR,BCH/BTC,ETH/BTC,LTC/BTC,XRP/BTC
FTX      :  BTC/USDT,BTC/USD,ETH/USDT,ETH/USD,LTC/USDT,LTC/USD,BNB/USDT,BNB/USD,XRP/USDT,XRP/USD,LINK/USDT,LINK/USD,BCH/USDT,BCH/USD,TRX/USDT,TRX/USD
GEMINI   :  BTC/USD,ETH/USD,LTC/USD,ETH/BTC,ZEC/USD,ZEC/BTC,ZEC/ETH
KUCOIN   :  BTC/USDT,ETH/USDT,LTC/USDT,NEO/USDT,BNB/USDT,XRP/USDT,EOS/USDT,TRX/USDT,ZEC/USDT,ADA/USDT,DASH/USDT,BCH/USDT,XTZ/USDT,BTC/USDC
POLONIEX :  BTC/USD,ETH/USDT,LTC/USDT,XRP/USDT,BCH/USDT,XMR/USD,DASH/USDT,ETC/USDT,BAT/USDT,ZRX/USDT,EOS/USDT,LSK/USDT,REP/USDT,XRP/BTC,ETH/BTC,LTC/BTC,XMR/BTC

Pair     :  BTC, ETH, EUR, GBP, JPY, USD, USDC, USDT

Time series : d, 1h
"""

# Example -> Binance_BTCUSDT_d.csv
exchange_name = 'Binance'
coin_name = 'BTC'.upper()
pair_name = 'USDT'.upper()
time_series = 'd'.lower()  # 'd' and '1h' available
file_name = str(exchange_name + "_" + coin_name + pair_name + "_" + time_series)
full_filename = str(exchange_name + "_" + coin_name + pair_name + "_" + time_series + ".csv")
exc_pair = coin_name + "/" + pair_name


def check_names():
    binance = "BTC/USDT,ETH/USDT,LTC/USDT,NEO/USDT,BNB/USDT,XRP/USDT,LINK/USDT,EOS/USDT,TRX/USDT,ETC/USDT,XLM/USDT,ZEC/USDT,ADA/USDT,QTUM/USDT,DASH/USDT,XMR/USDT,BAT/USDT,BTT/USDT,ZEC/USDT,USDC/USDT,TUSD/USDT,MATIC/USDT,PAX/USDT,CELR/USDT,ONE/USDT,DOT/USDT,UNI/USDT,ICP/USDT,SOL/USDT,VET/USDT,FIL/USDT,AAVE/USDT,DAI/USDT,MKR/USDT,ICX/USDT,CVC/USDT,SC/USDT,LRC/USDT,ADA/BTC,AST/BTC,BTG/BTC,DASH/BTC,EOS/BTC,ETC/BTC,ETH/BTC,IOTA/BTC,LTC/BTC,NEO/BTC,STRAT/BTC,XMR/BTC,XLM/BTC,XRP/BTC,XLM/ETH,XMR/ETH,XRP/ETH,NEO/ETH,LSK/ETH,IOTA/ETH,ETC/ETH,DASH/ETH,BTG/ETH"
    bitfinex = "BTC/USD,ETH/USD,LTC/USD,AID/USD,BAT/USD,LTC/USD,DAI/USD,DASH/USD,EDO/USD,EOS/USD,ETC/USD,ETP/USD,NEO/USD,OMG/USD,QTUM/USD,REP/USD,TRX/USD,XLM/USD,XMR/USD,XVG/USD,BTC/EUR,ETH/EUR,EOS/EUR,NEO/EUR,TRX/EUR,XLM/EUR,XVG/EUR,BTC/GBP,ETH/GBP,EOS/GBP,NEO/GBP,TRX/GBP,XLM/GBP,XVG/GBP,BTC/JPY,ETH/JPY,EOS/JPY,NEO/JPY,TRX/JPY,XLM/JPY,XVG/JPY,ETH/BTC,LTC/BTC,XRP/BTC,DAI/BTC,DASH/BTC,EOS/BTC,OMG/BTC,REP/BTC,TRX/BTC,XMR/BTC"
    bitstamp = "BTC/USD,ETH/USD,LTC/USD,XRP/USD,BCH/USD,BTC/EUR,ETH/EUR,LTC/EUR,BCH/EUR,ETH/BTC,LTC/BTC,BCH/BTC,BTC/USD,BCH/USD,ETH/USD,LTC/USD,XRP/USD,BTC/EUR,BCH/EUR,ETH/EUR,LTC/EUR,XRP/EUR,BCH/BTC,ETH/BTC,LTC/BTC,XRP/BTC"
    ftx = "BTC/USDT,BTC/USD,ETH/USDT,ETH/USD,LTC/USDT,LTC/USD,BNB/USDT,BNB/USD,XRP/USDT,XRP/USD,LINK/USDT,LINK/USD,BCH/USDT,BCH/USD,TRX/USDT,TRX/USD"
    gemini = "BTC/USD,ETH/USD,LTC/USD,ETH/BTC,ZEC/USD,ZEC/BTC,ZEC/ETH"
    kucoin = "BTC/USDT,ETH/USDT,LTC/USDT,NEO/USDT,BNB/USDT,XRP/USDT,EOS/USDT,TRX/USDT,ZEC/USDT,ADA/USDT,DASH/USDT,BCH/USDT,XTZ/USDT,BTC/USDC"
    poloniex = "BTC/USD,ETH/USDT,LTC/USDT,XRP/USDT,BCH/USDT,XMR/USD,DASH/USDT,ETC/USDT,BAT/USDT,ZRX/USDT,EOS/USDT,LSK/USDT,REP/USDT,XRP/BTC,ETH/BTC,LTC/BTC,XMR/BTC"
    exc_dict = {"binance": binance, "bitfinex": bitfinex, "bitstamp": bitstamp, "ftx": ftx, "gemini": gemini,
                "kucoin": kucoin, "poloniex": poloniex}

    if exchange_name.lower() not in exc_dict:
        print(f"{exchange_name} not in exchange list.")
        sys.exit()

    if exc_pair not in exc_dict[exchange_name.lower()]:
        print(f"{exc_pair} pair not available.")
        sys.exit()

    if time_series not in ('d', '1h'):
        print("Time series should be 'd' for daily, '1h' for hourly. Please check 'time_series' variable")
        sys.exit()
